# Generated by Django 3.2.6 on 2021-09-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('email', models.EmailField(error_messages={'unique': 'A client with that email address already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('phone', models.CharField(error_messages={'unique': 'A client with that phone number already exists.'}, max_length=10, unique=True, verbose_name='phone number')),
                ('mobile', models.CharField(error_messages={'unique': 'A client with that mobile number exists.'}, max_length=10, unique=True, verbose_name='mobile number')),
                ('company_name', models.CharField(max_length=25, verbose_name='company name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('sales_contact', models.ForeignKey(error_messages={'limit_choices_to': 'This user is not part of the sales team.'}, limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='sales contact')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
